exports.signup = require('./signup')
exports.login = require('./login')
exports.getItems = require('./item')
exports.cart = require('./cart')
exports.admin = require('./admin')
exports.deliveryPerson = require('./delivery')
exports.placeOrder = require('./order')